import{a as g,S as w,i as n}from"./assets/vendor-38cc1e54.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&o(m)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();g.defaults.baseURL="https://pixabay.com/api";const h=async(s,t)=>{try{const a={params:{key:"45436198-db4764fd7ddf19e0d061d1cf8",q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15}};return await g.get("/",a)}catch(a){throw console.error("Error fetching images:",a),a}},f=s=>` <li class="gallery-card">
                <a class="gallery-link" href="${s.largeImageURL}">
                    <img class="gallery-img"
                    src="${s.webformatURL}" 
                    data-source="${s.largeImageURL}"
                    alt="${s.tags}"
                    />
                </a>
                <div class="wrapper">
                    <ul class="img-content-wrapper">
					    <li class="text-info">Likes<span class="number">${s.likes}</span></li>
					    <li class="text-info">Views<span class="number">${s.views}</span></li>
					    <li class="text-info">Comments<span class="number">${s.comments}</span></li>
					    <li class="text-info">Downloads<span class="number">${s.downloads}</span></li>
                    </ul>
                </div>
            </li>`,l=document.querySelector(".js-search-form"),c=document.querySelector(".js-gallery"),y=document.querySelector(".loader"),u=document.querySelector(".js-load-more");let i=1,d="",p=0;const L=new w(".js-gallery a",{overlay:!0,captionsData:"alt",overlayOpacity:.8,captionDelay:250,focus:!0});function b(){y.classList.remove("is-hidden")}function v(){y.classList.add("is-hidden")}const S=async s=>{s.preventDefault(),b(),d=l.elements.user_query.value.trim(),i=1;try{const t=await h(d,i);if(d===""){n.warning({title:"Caution",message:"Input field must not be empty",position:"topLeft"});return}if(t.data.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"bottomRight"}),c.innerHTML="",l.reset();return}const a=t.data.hits.map(r=>f(r)).join("");c.innerHTML=a;const o=c.querySelector("li");console.log(o.getBoundingClientRect()),p=o.getBoundingClientRect().height,u.classList.remove("is-hidden"),L.refresh();const e=Math.ceil(t.data.totalHits/15);i>=e&&(u.classList.add("is-hidden"),n.info({title:"Info",message:"We are sorry,but you have reached the end of search results"}))}catch{n.error({title:"Error",message:"Illegal operation"})}finally{v()}l.reset()};l.addEventListener("submit",S);const P=async s=>{b();try{i++;const t=await h(d,i);console.log(t);const a=t.data.hits.map(e=>f(e)).join("");c.insertAdjacentHTML("beforeend",a),scrollBy({top:p*2,behavior:"smooth"}),L.refresh();const o=Math.ceil(t.data.totalHits/15);i>=o&&(u.classList.add("is-hidden"),n.info({title:"Info",message:"We are sorry,but you have reached the end of search results"})),l.reset()}catch(t){console.log(t),n.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}};u.addEventListener("click",P);
//# sourceMappingURL=commonHelpers.js.map
